variable "CIDR_BLOCK" {}
variable "SUBNET_CIDR_BLOCK" {}
variable "COMPONENT" {}
variable "ENV" {}
variable "AZ" {}
variable "PROJECT_NAME" {}
variable "ENGINE" {}
variable "NODE_TYPE" {}
variable "NUM_CACHE_NODES" {}
variable "ENGINE_VERSION" {}
variable "FAMILY" {}
variable "PORT" {}
variable "SKIP_FINAL_SNAPSHOT" {}
variable "INSTANCE_CLASS" {}
variable "NODE_COUNT" {}